### PR TITLE
Changed ajax dependency to vue-resource instead of jQuery

### PR DESCRIPTION
**Pull request by garhbod**
Only lightly tested

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Hi @garhbod - Thanks for this! Since [Evan You retired vue-resource and suggested to use axios instead](https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4) I think vue-model should follow this and replace $.ajax with axios instead of vue-resource. I already started to use axios for some tests which were based on your changes. Cheers for that. I will provide an axios implementation if @aarondfrancis has nothing against it and will close this PR for now.

**Comment by JonasDoebertin** [comment]
@thorsteneckel Any chance to get a hold of your axios implementation?

**Comment by thorsteneckel** [comment]
Sure! I'll create a branch and let you know. Should be done next week.

**Comment by JonasDoebertin** [comment]
Thanks!

**Pull request closed without merging**
